name: sixvalley_vendor_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  provider: ^6.1.5
  #connectivity: ^3.0.3
  connectivity_plus: ^5.0.2
  dio: ^5.9.0
  intl: any
  #flutter_html_to_pdf: ^0.7.0
  flutter_html_to_pdf_plus: ^0.3.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_switch: ^0.3.2
  fl_chart: ^1.0.0
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: any #^0.4.1
  flutter_typeahead: ^5.2.0
  autocomplete_textfield: ^2.0.1
  dotted_border: ^2.1.0
  flutter_layout_grid: ^2.0.8
  flutter_html: ^3.0.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.3.1
  path_provider: ^2.1.5
  country_code_picker: ^3.3.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.12
  permission_handler: ^12.0.1
  flutter_downloader: ^1.12.0
  barcode_widget: ^2.0.4
  # file_picker: ^4.3.0
  #open_filex: any
  #webview_flutter_plus:
  flutter_inappwebview: ^6.1.5
  device_info_plus: any
  url_launcher: ^6.3.2
  flutter_spinkit: ^5.2.2
  percent_indicator: ^4.2.5
  flutter_speed_dial: ^7.0.0
  #flutter_barcode_scanner: ^2.0.0
  flutter_barcode_scanner_plus: ^3.0.8
  #flutter_pos_printer_platform: ^1.4.2
  flutter_pos_printer_platform_image_3: ^1.2.4
  esc_pos_utils: ^1.1.0
  flutter_slidable: ^4.0.0
  readmore: ^3.0.0
  flutter_html_table: ^3.0.0
  google_maps_flutter: ^2.12.3
  syncfusion_flutter_datepicker: ^30.1.38
  textfield_tags: any
  http: any
  path: ^1.9.0
  razorpay_flutter:
  typed_data: ^1.4.0
  http_parser: ^4.1.2
  image_cropper: ^9.1.0
  animated_floating_buttons: ^0.0.2
  carousel_slider: ^5.1.1
  time_picker_sheet: ^0.0.2+1
  dropdown_button2: ^2.3.9
  sizer: ^3.0.5
  multi_dropdown: ^3.0.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_google_maps_webservices: any
  sms_autofill: ^2.4.1
  #google_maps_place_picker_mb: ^3.0.0
  map_location_picker: ^2.0.0+2


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/ubuntu/Ubuntu-Bold.ttf
          weight: 600